### ISSUE TITLE
JDK16 Triage push Coordination

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#2252]
Failing Test Buckets & Triager:
- OpenJDK - Adam Farley
- Functional - Andrew Leonard
- Performance - Simon Rushton
- System - Simon Rushton

Each triager to create a comment identifying failures they're working on, with test links, issue links, platforms, etc.

**Comment by lumpfish** [comment]
Issues affecting Performance (sanity all pass - these affect extended (i.e. weekly / release)):
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2253
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2254
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2255

**Comment by lumpfish** [comment]
These are machine specific issues cause system test failures if a particular test lands on a particular machine:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1907
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1851
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1777
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1673

This is an unresolved intermittent issue which occurs rarely:
https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/274

**Comment by andrew-m-leonard** [comment]
extended.functional AIX "Dump" failures:
    org.openj9.test.attachAPI.TestJcmd.testDumps
    org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings
    org.openj9.test.attachAPI.TestJcmd.testDumpsWithOptions
    org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testLocal_triggerDump
    org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testRemote_triggerDumpToFile
    org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testRemote_triggerDump
    org.openj9.test.java.lang.management.TestOpenJ9DiagnosticsMXBean.testLocal_triggerDumpToFile

Grinders of TestJcmd_0 on the 4 AIX boxes:
 https://ci.adoptopenjdk.net/job/Grinder/6696/
 https://ci.adoptopenjdk.net/job/Grinder/6697/
 https://ci.adoptopenjdk.net/job/Grinder/6698/
 https://ci.adoptopenjdk.net/job/Grinder/6699/
**Bad:**
build-osuosl-aix71-ppc64-2
**Good:**
test-ibm-aix71-ppc64-2

**Comment by andrew-m-leonard** [comment]
extended.functional xLinux testDDRExt_Class_0:
Possibly unique to node: test-docker-ubuntu1804-x64-1
Grinder across 6 nodes:
https://ci.adoptopenjdk.net/job/Grinder/6700/
https://ci.adoptopenjdk.net/job/Grinder/6701/
https://ci.adoptopenjdk.net/job/Grinder/6702/
https://ci.adoptopenjdk.net/job/Grinder/6703/
https://ci.adoptopenjdk.net/job/Grinder/6704/
https://ci.adoptopenjdk.net/job/Grinder/6705/

**Comment by lumpfish** [comment]
Other machine specific test failures already raised for openjdk / functional test failures:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1819
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1907
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1916
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1918

**Comment by adamfarley** [comment]
OpenJDK issues:
- aarch64
  - jdk_lang_0 - TestLambdaFileEncodingSerialization failure ([Example](https://trss.adoptopenjdk.net/output/test?id=601ea2ce217ed804cc8a6d6a)) - https://github.com/eclipse/openj9/issues/11915
  - jdk_util_0 - CountLargeTest.java failure ([Example](https://trss.adoptopenjdk.net/output/test?id=601e9f78217ed804cc8a1bc4)) - Excluded as per https://github.com/AdoptOpenJDK/openjdk-tests/pull/2243
  - jdk11_tier1_cipher_0 - GCMBufferTest.java failure ([Example](https://trss.adoptopenjdk.net/output/test?id=601e9f78217ed804cc8a1bcd)) - Fixed by [this PR](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/266) once it's finished and subsequently backported. Peter Shipton is aware of the need to backport, as per [this issue](https://github.com/eclipse/openj9/issues/11391).

**Comment by lumpfish** [comment]
jdk-16+36_openj9-0.25.0-m2 triage

Failing jobs and their issues:

TRSS ppc64_aix: https://trss.adoptopenjdk.net/resultSummary?parentId=603cc5345730424dbc98db6c

**ppc64_aix**

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/31/consoleFull
Issues:
https://github.com/eclipse/openj9/issues/11738
https://github.com/eclipse/openj9/issues/10990

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_ppc64_aix/7/console
Issues:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2253


TRSS Other platforms: https://trss.adoptopenjdk.net/resultSummary?parentId=603cc5345730424dbc98db6e

https://github.com/AdoptOpenJDK/openjdk-tests/issues/2253 affects extended.perf jobs on all platforms

**aarch64_linux**

Respin required due to missing PR: https://github.com/eclipse/openj9/pull/11987

ppc64le_linux

**Failing job:**
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.external_ppc64le_linux/4/
Issues:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2317

**s390x_linux**

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.external_s390x_linux/4/
Issues:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2317

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_s390x_linux/9/consoleFull
Issues:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1992

**x86-64_linux**

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.external_x86-64_linux/4/

Issues:
https://github.com/eclipse/openj9/issues/12038
https://github.com/eclipse/openj9/issues/12099

**x86-64_mac**

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_x86-64_mac/9/consoleFull
Issues:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2327

**Comment by lumpfish** [comment]
jdk-16+36_openj9-0.25.0-m3 triage (aarch64_linux)

TRSS: https://trss.adoptopenjdk.net/resultSummary?parentId=603f73945730424dbc9ad608

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_aarch64_linux/41/consoleIssues:
Issues:
https://github.com/eclipse/openj9/issues/11915

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_aarch64_linux/10/consoleFull
Issues:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2002

Failing job:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.system_aarch64_linux/42/consoleFull
Issues:
https://github.com/eclipse/openj9/issues/12124

**Comment by smlambert** [comment]
Closing this as stale (and as it was a working document for a now retired build).
