### ISSUE TITLE
Move download jtreg.jar logic in getDependencies

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2484]
Currently, we download jtreg jar in [openjdk/build.xml](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L57) at build runtime. The downloading step may fail due to the network issue. And if this happens, the test build will fail.

```
00:14:19.779  getJtreg:
00:14:19.779      [mkdir] Created dir: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux/jvmtest/openjdk
00:14:19.779       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/jtreg-4.2.0-tip.tar.gz
00:14:29.796 
      [exec] curl: (18) transfer closed with 4584692 bytes remaining to read
00:14:29.796  
00:14:29.796  BUILD FAILED
```

We should move Move download jtreg.jar logic in [getDependencies.pl](https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl). It means that the jar will be pre-downloaded in Jenkins job (i.e., https://ci.adoptopenjdk.net/job/test.getDependency/). During the build execution time, the jar will be copied into the test build. If for whatever reason the jar does not exist (i.e., test.getDependency job does not have the pre-downloaded jar, local runs, etc), the script will try to download it again at runtime.

**Comment by vanichitkara** [comment]
Hi, I'd like to work on this issue. Can I be assigned with it? Thanks!

**Comment by smlambert** [comment]
Yes, defininitely @vanichitkara !

**Comment by vanichitkara** [comment]
Hi! I was working on the issue and noticed that getDependencies.pl file is in Perl and I'm not familiar with Perl at all. CanI get some help regarding this issue? Thanks!

**Comment by karianna** [comment]
> Hi! I was working on the issue and noticed that getDependencies.pl file is in Perl and I'm not familiar with Perl at all. CanI get some help regarding this issue? Thanks!

Recommend asking on our Slack group to get more eyes :-)

**Comment by smlambert** [comment]
More details:
We want to change how we download a dependency called jtreg.

It is currently being downloaded via the ant script called openjdk/build.xml file (see the ant target called getJtreg at https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L30-L79)

But instead of downloading it there, we want to fetch it in the getDependencies.pl script.  Notice that dependencies in this perl script are added to the %base hashmap, see this example for the osgi dependency: https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl#L127-L131

So, I believe to fix this issue, you will need two PRs, one for this repo, to remove the getJtreg ant target (L30-79) from the build.xml file, and one in the TKG repo, for adding some logic to the perl script.  

If we were downloading a single version of jtreg, it would be simply to add some lines to the %base hashmap, but the logic in the ant script says "if a certain version of java, then download jtreg4.2.0, if other versions of java then download jtreg5.1.b101, so there would be some logic needed to check version and set a variable with the jtregVersion, where jtregVersion is set either to jtreg-5.1-b01 or jtreg-4.2.0-tip

```
jtreg => {
		url => "https://ci.adoptopenjdk.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/$jtregVersion.tar.gz",
		fname => 'jtreg.tar.gz',
		shaurl => "https://ci.adoptopenjdk.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/$jtregVersion.tar.gz.sha256sum.txt",
		shafn => "$jtregVersion.tar.gz.sha256sum.txt",
		shaalg => '256'
	},

```

One other 'gotcha', the getJtreg ant target also called gzip to unzip the tar.gz file (see https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L61-L62), that will likely also have to be done in the perl script, maybe in the downloadFile function (https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl#L252) with logic if file ends in tar.gz, then run gzip on the file.

**Comment by llxia** [comment]
All PRs are delivered. Close this issue.
