### ISSUE TITLE
Rerun in Grinder links populate Parameter Separators and Help Text as String params

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2681]
The [code used to generate the rerun in Grinder links](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L877-L887) loops through all params and presents them as String params.  

If it is possible, for Parameter separators types it would be preferred to keep them as their original type, or remove them from the set of parameters that get set in the Grinder job that is set up with rerun link.

**Comment by gervaisj** [comment]
@llxia I've been trying to get this done by basing the filtering by the parameter type (which is the most maintainable way imo), which in our case should be [`ParameterSeparatorDefinition`](https://javadoc.jenkins.io/plugin/parameter-separator/jenkins/plugins/parameter_separator/ParameterSeparatorDefinition.html) but the exposed `params` object provided to jenkins steps is devoid of any type information: it becomes a `Map<String, Object>` with immutable entries (`Object` here is `String` or `Boolean` or `Integer`, no info about separators here...). This is also why Mercon55's solution did not work.

I've been looking at documentation for a few hours now, and every way I find to get the "raw" declared parameters of the pipeline, or any type info, these methods are disabled and grinder returns a `org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException` exception.

Would it be possible to enable one of them? Specifically, the static method `hudson.model.ParameterDefinition.all()` would be the most direct route. It would give me access directly to all the parameter definitions and I could use them to filter.
Otherwise, I can simple declare a list of excluded parameter keys (literally copy-pasting from [testJobTemplate](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate)) to filter.
Or, of course, if you know of a better way of doing this, let me know!

**Comment by gervaisj** [comment]
The goal of this issue was not only to remove the parameters from link, but to correct the display of the form when clicking on the link (separators and help text have text boxes next to them).

![image](https://user-images.githubusercontent.com/50028573/150658019-0eee996c-f51f-4785-a9aa-149b810740fc.png)

https://github.com/adoptium/aqa-tests/pull/3273 fixes part of the issue by removing the parameters from the link, but as discovered, the rendering of the form is controlled by another plugin, namely [Build With Parameters](https://plugins.jenkins.io/build-with-parameters/) which does not recognize our other plugin's ([Parameter Separator](https://plugins.jenkins.io/parameter-separator/)) special `ParameterSeparatorDefinition` class (see [this code](https://github.com/jenkinsci/build-with-parameters-plugin/blob/655d9561730f8ce7891c9cc80959d043f878ebeb/src/main/java/org/jenkinsci/plugins/buildwithparameters/BuildWithParametersAction.java#L53) for example).

So we would need to convince the authors of Build With Parameters to change their rendering in order to complete this issue fully.
