### ISSUE TITLE
Add a link to Grinder wiki in testJobTemplate

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2683]
We should add a link to Grinder wiki https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins in testJobTemplate https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate

Grinder wiki contains a more detailed description/examples of the parameters.

**Comment by smlambert** [comment]
One way to address this issue is to add that Grinder link to the description of the generated job, which shows up right at the top of a generated job page.

So, updating the description at https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L196 to have an extra sentence at the end that says "For more information about job parameters, see https://github.com/adoptium/aqa-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins"

**Comment by ManasviGoyal** [comment]
working on this

**Comment by ManasviGoyal** [comment]
@smlambert done. please check

**Comment by smlambert** [comment]
Not sure why that error is thrown, when I rerun the ECA validation it passes, but doesn't explain why it fails on first try.

**Comment by ManasviGoyal** [comment]
> Not sure why that error is thrown, when I rerun the ECA validation it passes, but doesn't explain why it fails on first try.

So, do I need to make any changes or it works fine now?

**Comment by smlambert** [comment]
It is now marked as 'passed', so no action from you is needed.
