### ISSUE TITLE
Minor Enhancement in README.md

### ISSUE THREAD

**Issue by Ayushdubey86** [adoptium/aqa-tests#2725]
There are several minor issues in the README.md that need to be fixed for the enhancement of the documentation.

**Comment by Ayushdubey86** [comment]
Wait, I'll commit some changes and will revert back at you

**Comment by smlambert** [comment]
Hi @Ayushdubey86 - if you are looking to take on a good first issue, please have a look at the ones listed in https://github.com/orgs/adoptium/projects/2. 

With reference to this issue, I have looked at your changes to the README and will not merge them.  I will also close this issue as it can be addressed under issue https://github.com/adoptium/aqa-tests/issues/1558, since we need to do an overhaul of the documentation and this is best done by a core committer given that some of the information also needs to be updated.
