### ISSUE TITLE
MBCS_Tests_annotation_Ja_JP_aix_0 target from special.functional fails on AIX

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2763]
Deep history of this test target: https://trss.adoptium.net/deepHistory?testId=60f7826273f1507c79eed3d7
shows it was passing at some point in the past (Jan 20, 2021?) on test-ibm-aix71-ppc64-1.

Rerun in grinder on test-ibm-aix71-ppc64-1 using July release build fails - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1133/ 

Not sure if this is a change to the AIX machines (if these MBCS tests require special setup on AIX machines), or if there is a real issue being shown by this failure.

**Comment by smlambert** [comment]
FYI @takiguc @KKES335

**Comment by takiguc** [comment]
@smlambert 
This issue is related following issue, and it's not backported to JDK8.
[JDK-8202329](https://bugs.openjdk.java.net/browse/JDK-8202329) Codepage mappings for IBM-943 and Big5 (aix)
This issue is just for hotspot jvm, openj9 jvm works fiine without this code.
annotation testcase should be executed by 11+ on AIX Ja_JP locale.
I'd like to handle this issue.
Thanks.

**Comment by smlambert** [comment]
Thanks for the clarification and assistance @takiguc !
