### ISSUE TITLE
Add hotspot_custom for hotspot component

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2878]
It would be nice to add hotspot specific custom testcase, which would enable us to run a specific hotspot test or hostspot tests under specific path easily in jenkins grinder.

Adding hotspot_custom is really similar to add langtools_custom testcase, https://github.com/adoptium/aqa-tests/issues/2692#issuecomment-870844104 .

**Comment by unnati914** [comment]
could i work on this?

**Comment by unnati914** [comment]
@sophia-guo

**Comment by smlambert** [comment]
Go for it @unnati914 !

**Comment by unnati914** [comment]
I have to do something similar to #2743 right?

**Comment by smlambert** [comment]
2743 links to the issue that describes it better: https://github.com/adoptium/aqa-tests/issues/2692 

@sophia-guo can clarify best, but I believe this issue is to add support for hotspot_custom target, which will require these changes:

- adding a `<test><testCaseName>hotspot_custom</testCaseName>...</test>` to a playlist.xml file (in the same playlist.xml file that the [jdk_custom](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L17-L38) target lives, likely just below it in the file).  
- Then in the `<command>` of the new test target, using [JTREG_HOTSPOT_TEST_DIR ](https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L109) variable in place of [JTREG_JDK_TEST_DIR](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L30)

**Comment by sophia-guo** [comment]
@unnati914 yes, please see @smlambert comment  https://github.com/adoptium/aqa-tests/issues/2878#issuecomment-922853843.

**Comment by smlambert** [comment]
Clearing assignee as we have not heard back!

**Comment by sophia-guo** [comment]
The default testcase can be set as `gc/stress/gclocker/TestExcessGCLockerCollections.java`

**Comment by sophia-guo** [comment]
Before line 114 [ifneq (,$(findstring $(JDK_VERSION),8-9))](https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L114 set  HOTSPOT_CUSTOM_TARGET default value `HOTSPOT_CUSTOM_TARGET ?= gc/stress/gclocker/TestExcessGCLockerCollections.java`
