### ISSUE TITLE
Dynamically map platforms from ProblemList to PLATFORM

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2910]
Currently, we have a [hardcoded map ](https://github.com/adoptium/aqa-tests/blob/master/disabledTestParser/generateDisabledTestListJson.py#L7) to map [platform value in problem list](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk11-openj9.txt#L30) to [PLATFORM](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L3). For enhancement, I think we can map this dynamically. We can split the platform value in the problem list by -. The matching PLATFORM should contain the tokens with a few exceptions.

Related: https://github.com/adoptium/aqa-tests/issues/2698

**Comment by prahasR** [comment]
Hi @llxia can you please elaborate a little more over this. What exactly do you mean by dynamical mapping? I am getting it as that the "platform_map" is a dictionary that stores string as keys and list as values. So you want to split the keys by - and then map the splitted keys to the list?

**Comment by llxia** [comment]
For example, if we get `linux-ppc32`, we can set `PLATFORM` to be `ppc32_linux` by split the value using `-` and reverse the first and the second token. We do not really need a hardcoded map.

There are a few mistakes in the map:
https://github.com/adoptium/aqa-tests/blob/master/disabledTestParser/generateDisabledTestListJson.py#L8
https://github.com/adoptium/aqa-tests/blob/master/disabledTestParser/generateDisabledTestListJson.py#L17

You can ignore them for now. They should be fixed in https://github.com/adoptium/aqa-tests/issues/2908

**Comment by prahasR** [comment]
I think that one of the possible solution is to directly add the result we get by doing above mentioned operation over `unresolved_platform_name` in the `revolved_platform_list` instead of doing it by `if-elif` conditions here https://github.com/adoptium/aqa-tests/blob/master/disabledTestParser/generateDisabledTestListJson.py#L49. I am working toward this @llxia, please assign this issue to me.

**Comment by prahasR** [comment]
Is the solution seems correct to you? Should I start working toward this @llxia ?

**Comment by gervaisj** [comment]
I'd like to work on this.

@llxia transforming the platform and eliminating the map should be fairly easy, but there's one tricky thing: currently, when the platform is a `*-all` (`generic-all`, `linux-all`, etc.), we use the map to expand it to a list of "concrete platforms" (`aarch64_linux`, `x86-64_linux`, etc.).

1. Should I copy the same platforms chosen when we run Grinder with PLATFORM=all and filter for linux, windows, mac, aix if needed? https://github.com/adoptium/aqa-tests/blob/253c7bf6fb188ca14c46bc13b2cc5426e13a12ea/buildenv/jenkins/openjdk_tests#L117-L123
2. If a platform in an exclude file is already in the right `{ARCH}_{OS}` format (instead of the `{OS}-{ARCH}` format), I don't think it's fair for the script to stop completely. Should we simply log a warning and keep going with the value? I could detect the `{ARCH}_{OS}` format by splitting on `_` and asserting the len is 2.
3. I'd also like to refactor the code a little bit by introducing some data types, logging and taking stdin/stdout as default input/output streams (instead of "../openjdk/excludes" and `getcwd()`). Am I free to open a separate PR after the one for this issue, or should all the work be tracked with an issue?

**Comment by gervaisj** [comment]
@llxia just poking for the comment above https://github.com/adoptium/aqa-tests/issues/2910#issuecomment-1025730571 I'd like some feedback before opening any PR.

**Comment by llxia** [comment]
Thanks @gervaisj 
1. yes, we can set PLATFORM=all and let Jenkins script handle it
2. Do you see any `{ARCH}_{OS}` format in the exclude list? If you do, can you list them? It may be a mistake. 
>  Should we simply log a warning and keep going with the value?

yes, that is correct.

3. Yes, please feel free to open separate PR for refactoring. IMO, it is better to have separate PRs in this case.

**Comment by gervaisj** [comment]
> Thanks @gervaisj
> 
> 1. yes, we can set PLATFORM=all and let Jenkins script handle it
> 2. Do you see any `{ARCH}_{OS}` format in the exclude file? If you do, can you list them? There may be some mistakes.
> 
> > Should we simply log a warning and keep going with the value?
> 
> yes, that is correct.
> 
> 3. Yes, please feel free to open separate PR for refactoring. IMO, it is better to have separate PRs in this case.

@llxia 

1. I was proposing, when we see `linux-all` in the exclude file, to set `PLATFORM=linux-all` in the output JSON (same for `windows-all`, `macos-all`, `aix-all`, `sunos-all`), and update Jenkins to handle these sorts of values, but we should always set `PLATFORM=all` regardless of the requested OS?
2. If I understood our format correctly, all the problems I saw were in "ProblemList_openjdk18.txt": `linux_ppc64le` should be `linux-ppc64le`, `linux_s390x` should be `linux-s390x`, `win_64` should be `windows-x64`, and on line 403 `ppc64le_linux` is already formatted.
Ok, I'll log a warning anytime I see a `_` and blindly assume the platform is correct (worst thing that can happen is Jenkins will say it doesn't recognize the platform)
3. In a separate PR, super!
