### ISSUE TITLE
Add processing for special characters in JVM options 

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-tests#321]
Any mode with Quote (") characters will not work on STF based tests (e.g. systemtest or jck test). For example, the following build was run with : -Xjit:counts="- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000", and it fails:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/401/console

For any jvm option that contains quote, we need special processing similar to that in https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/makefile. We can have a simple make file that only contains quote character processing for mode strings.

**Comment by smlambert** [comment]
Did https://github.com/adoptium/aqa-tests/pull/317 address this sufficiently?  This issue is very old, I doubt we will do anything more with this.  I believe we have documentation in Grinders to help people navigate passing of difficult special character options through the various frameworks we support.
