### ISSUE TITLE
Fix how external tests clean up Docker images

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3299]
External test jobs have been temporarily disabled from upstream pipeline. However if build job is triggered directly (not by pipeline) with default test list ( "sanity.openjdk", "sanity.system","extended.system", "sanity.perf", "sanity.external", https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/configure) https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/1103/ , external tests job will be triggered. https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk11_j9_sanity.external_x86-64_linux/515/console

External test jobs story has been changed to run as parallel ( or later dynamic?), the old default configuration doesn't set as parallel, which means the job will run all enabled external sanity jobs. However the task  [`docker_prune`](https://github.com/adoptium/aqa-tests/blob/master/external/build.xml#L54) will recursively run and delete all earlier generated docker images and failed the job. https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk11_j9_sanity.external_x86-64_linux/515/console

To avoid the confusion and prepare for re-enabling external tests, two steps can help

1. Update ci-pipeline-jenkins job config_regeneration to be consistent with nightlyDefault. 
2. Regenerate external test jobs to be latest and corresponding update to  parallel or dynamic.

@LongyuZhang noticed the failure in both adoptium and openj9 and questioned if any changes in external tests caused the failure

**Comment by LongyuZhang** [comment]
Some more details about the external tests failure:
- the docker image for a specific test (e.g. quarkus_quickstarts-test) was built successfully (e.g. adoptopenjdk-quarkus_quickstarts-test:11-jdk-ubuntu-openj9-full), but when building the next test (e.g. scala), its [`docker prune`](https://github.com/adoptium/aqa-tests/blob/5a03ab34317f557683252e38c35f675ae673bafa/external/build.xml#L54-L58) step deletes docker image for previous tests (e.g. quarkus_quickstarts-test), and caused testing for previous test (e.g. quarkus_quickstarts-test) failed since it cannot find the docker image.
- An example on Jenkins pipeline is [here](https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk11_j9_sanity.external_x86-64_linux/515/), with the following console output.

```
08:50:17       [exec] Successfully tagged adoptopenjdk-quarkus_quickstarts-test:11-jdk-ubuntu-openj9-full
08:50:17  
08:50:17  dist:
08:50:17       [copy] Copying 2 files to /home/jenkins/workspace/Test_openjdk11_j9_sanity.external_x86-64_linux/jvmtest/external/quarkus_quickstarts
08:50:17  
08:50:17  build:
08:50:17  
08:50:17  move_scripts:
08:50:17       [copy] Copying 1 file to /home/jenkins/workspace/Test_openjdk11_j9_sanity.external_x86-64_linux/jvmtest/external/scala/dockerfile
08:50:17  
08:50:17  docker_prune:
08:50:18       [exec] Deleted Images:
08:50:18       [exec] untagged: adoptopenjdk/openjdk11-openj9:ubuntu-nightly
08:50:18       [exec] untagged: adoptopenjdk/openjdk11-openj9@sha256:d61b310bd5fee13c708c20bbdc38ca3a25d2415a1a212fb71b5e7e10bff206a7
08:50:18       [exec] untagged: adoptopenjdk-quarkus_quickstarts-test:11-jdk-ubuntu-openj9-full
```
FYI @llxia @smlambert

**Comment by llxia** [comment]
Steps:
- remove `depends="docker_prune"` in https://github.com/adoptium/aqa-tests/blob/master/external/build.xml#L60
- add `docker_prune ` in https://github.com/adoptium/aqa-tests/blob/master/external/build.xml#L41
- run Grinder with TARGET=sanity.external on xlinux

**Comment by LizyBbethy** [comment]
i can take this on
