### ISSUE TITLE
quarkus_quickstarts_test_0 failed with jdk17

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3382]
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/442/console
quarkus_quickstarts_test_0 failed with jdk17.

```
20:00:35  /quarkus-quickstarts
20:00:35  Compile and run quarkus_quickstarts tests
20:00:35  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
20:00:38  [[1;31mERROR[m] Error executing Maven.
20:00:38  [[1;31mERROR[m] java.lang.IllegalStateException: Unable to load cache item
20:00:38  [[1;31mERROR[m] Caused by: Unable to load cache item
20:00:38  [[1;31mERROR[m] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
20:00:38  Build quarkus_quickstarts completed
```

**Comment by smlambert** [comment]
Suggest an update of quarkus version first, since we take a very old release at present (we are pulling [1.3.2.Final](https://github.com/adoptium/aqa-tests/blob/master/external/quarkus_quickstarts/test.properties#L11), and the latest tag looks to be [2.7.2.Final](https://github.com/quarkusio/quarkus-quickstarts/releases/tag/2.7.2.Final)).

**Comment by amir-waheed** [comment]
I can work on this issue.

**Comment by sophia-guo** [comment]
related with https://github.com/adoptium/aqa-tests/issues/3450

**Comment by sophia-guo** [comment]
Same failure as https://github.com/adoptium/aqa-tests/issues/3390Looks like this mvn version doesn't work with jdk17.
