### ISSUE TITLE
external test spring_test failed with jdk11 (passed with jdk17)

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3389]
external test spring_test failed with jdk11 (passed with jdk17)
jdk17: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/454/
jdk11: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/455/console

```
14:24:50  Building Spring  using gradle
14:24:50  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
14:26:08  
14:26:08  FAILURE: Build failed with an exception.
14:26:08  
14:26:08  * What went wrong:
14:26:08  Execution failed for task ':buildSrc:compileJava'.
14:26:08  > error: invalid source release: 17
14:26:08  
14:26:08  * Try:
14:26:08  > Run with --stacktrace option to get the stack trace.
14:26:08  > Run with --info or --debug option to get more log output.
14:26:08  > Run with --scan to get full insights.
```

Looks like jdk17 is required for compile?

**Comment by smlambert** [comment]
We currently are not using the latest stable build which appears to be https://github.com/spring-projects/spring-boot/releases/tag/v2.6.4.  We likely should switch to using it by adding a line `tag_version="v2.6.4"` to the [spring/test.properties](https://github.com/adoptium/aqa-tests/blob/master/external/spring/test.properties) file.

We may still see the issue being reported, but at least we are pulling a stable build (otherwise we are just pulling from master/main branch).

**Comment by sophia-guo** [comment]
For release v2.6.4 I can see [sourceCompatibility = 1.8](https://github.com/spring-projects/spring-boot/blob/v2.6.4/buildSrc/build.gradle#L13), while in default main branch [sourceCompatibility = 17](https://github.com/spring-projects/spring-boot/blob/main/buildSrc/build.gradle#L13).  Tag stable version should fix this.

**Comment by amir-waheed** [comment]
I can work on this issue.
