### ISSUE TITLE
Update AutoReenableJob

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3445]
- Update AutoReenableJob to use the latest python script in https://github.com/adoptium/aqa-tests/tree/master/scripts/disabled_tests
- Consume git token. For example:
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L485
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L494

https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/triggerGrinder.groovy

**Comment by amir-waheed** [comment]
Can I be assigned to the issue?

**Comment by gervaisj** [comment]
@amir-waheed The playlist parser is now merged https://github.com/adoptium/aqa-tests/pull/3460, so you'll be able to integrate that as well.

I did a trial run of what we have so far. See this run: https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/133. I think the only things to change would be:
- to run the tests in parallel
https://github.com/adoptium/aqa-tests/blob/2c680a91f29ccc665b546696300b3f9fc1fcaa20/buildenv/jenkins/openjdk_tests#L147-L153
- the `infile` to `issue_status.py` should be `${WORKSPACE}/aqa-tests/scripts/disabled_tests/problem_list.json` (instead of the shorter path).


@llxia As far as I can tell, we just need to be able to install the Python requirements on the Jenkins machines (I had to "`git clone && python setup.py`" packages to do a trial run) to really go forward with this.

**Comment by amir-waheed** [comment]
@gervaisj Thank you for the suggestions. I have made relevant changes on my branch and it seems to be working :)
