### ISSUE TITLE
jdk/jfr/jcmd/TestJcmdDump.java.TestJcmdDump consistently failing in jdk18+36 Release Triage

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3492]
The test jdk/jfr/jcmd/TestJcmdDump.java.TestJcmdDump.java.TestJcmdDump from the extended openjdk test suite continues to fail across some platforms

```
java.lang.OutOfMemoryError: Java heap space
	at jdk.jfr.jcmd.TestJcmdDump.jfrDump(TestJcmdDump.java:106)
	at jdk.jfr.jcmd.TestJcmdDump.main(TestJcmdDump.java:87)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000800c02000.invokeStatic(LambdaForm$DMH)
```

MacOS https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_0/27/
Trss 

Linux aarch64 https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_linux/27/testReport/jdk_jfr_jcmd_TestJcmdDump/java/TestJcmdDump/
Trss https://trss.adoptium.net/output/test?id=623aa15c72761a4c5cf7c523

linux ppc64le 
Trss https://trss.adoptium.net/output/test?id=623a740572761a4c5cf761e6
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_ppc64le_linux_testList_0/27/testReport/

Linux s390x https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_0/25/testReport/jdk_jfr_jcmd_TestJcmdDump/java/TestJcmdDump/
Trss https://trss.adoptium.net/output/test?id=623a657772761a4c5cf73e09

**Comment by Haroon-Khel** [comment]
Just found that the test is excluded on aarch64-linux,linux_ppc64le and linux_s390x (yet still ran during this release) https://github.com/adoptium/aqa-tests/blob/69aaa7007e46165aac73af50052dd42e9d29a7ca/openjdk/excludes/ProblemList_openjdk18.txt#L399

MacOS should also be added to the exclude list

**Comment by Haroon-Khel** [comment]
Closing as it appears to be intermittent on MacOS 
Recent pass https://ci.adoptopenjdk.net/job/Grinder/3914/console

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/133#issuecomment-1076456053 

> Test issue raised https://github.com/adoptium/aqa-tests/issues/3492
Test is excluded for jdk18 on this platform https://github.com/adoptium/aqa-tests/blob/69aaa7007e46165aac73af50052dd42e9d29a7ca/openjdk/excludes/ProblemList_openjdk18.txt#L399

If the test was excluded (via https://github.com/adoptium/aqa-tests/pull/3044), it should not have run.  Since it is running and failing, looking at how it was excluded shows us that it was not excluded properly (wrong platform name used).  This particular test case is NOT a very nice one to include in the AQA suite, as it appears to be very sensitive to machine resource (therefore is flaky / intermittently failing depending on which machine it lands on).  We can switch the entry in the ProblemList file to generic-all and exclude on all platforms (until the test itself can be improved to be able to run on a variety of machines).

Going to reopen this issue and use it as the base issue for the exclusion (rather than https://github.com/adoptium/aqa-tests/issues/2919 which is more generic).

**Comment by sophia-guo** [comment]
Check all history it shows test only failed with non-compressed. Might be worth to check if it should be enabled for non-compressed.

**Comment by sophia-guo** [comment]
windows too. https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1/33/

**Comment by sophia-guo** [comment]
Not reproduced in recent run https://github.com/adoptium/aqa-tests/issues/4352#issuecomment-1915204757

**Comment by sophia-guo** [comment]
This still happens intermittently. https://github.com/adoptium/aqa-tests/issues/5444.

As it only happened to non-compressed https://github.com/adoptium/aqa-tests/issues/3492#issuecomment-1115459921, https://adoptium.slack.com/archives/C5219G28G/p1731569159139549 suggests to increase the -Xmx.
