### ISSUE TITLE
jdk_nio_0 and java_nio_1 BlockingChannelOps times out on ppc64 aix for Java 19

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3983]
[TRSS Test Output](https://trss.adoptium.net/output/test?id=632bf1c193ac60470bc85542) and 
[TRSS Test Output](https://trss.adoptium.net/output/test?id=632bf1c193ac60470bc85543)

**Comment by smlambert** [comment]
This is due to vthread testcases failing as unsupported on AIX.

Similar to https://github.com/adoptium/aqa-tests/issues/3981, the action to take is to exclude the failing jdk_nio test cases on AIX.  This can be done by updating the ProblemList at the end of the jdk_nio section (https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk19.txt#L238) with the following:

```
java/nio/channels/vthread/BlockingChannelOps.java#id0 https://github.com/adoptium/aqa-tests/issues/4024 aix-all
```

**Comment by Adeosunomoshalewa** [comment]
i'd like to work on this issue
