### ISSUE TITLE
Add new security tests (Part 2: ssl-tests)

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4403]
Related to https://github.com/adoptium/aqa-tests/issues/3829 - this issue encapsulates the desire to add this set of tests:
https://github.com/rh-openjdk/ssl-tests to AQAvit.  

To resolve this issue, we can follow the same approach as was done in Part 1: CryptoTests resolved by this https://github.com/adoptium/aqa-tests/pull/4327 (which resolved https://github.com/adoptium/aqa-tests/issues/4356).

**Comment by zzambers** [comment]
ssl-tests should now be ready for inclusion. Jtreg scripts are located in [jtreg-wrappers](https://github.com/rh-openjdk/ssl-tests/tree/master/jtreg-wrappers) directory in project repo. In GH actions Temurins (8,11,17,19) are [passing](https://github.com/rh-openjdk/ssl-tests/actions/runs/4380575311) on linux/win/macos and also linux+jtreg. 

Dependencies:
- all variants are `make` and `openssl` tools
- `ssl-tests-gnutls-client.sh` (linux only) additionally needs `gnutls-bin` package (ubuntu)
- `ssl-tests-nss-client.sh` (linux only) additionally needs `libnss3` `libnss3-tools` `libnss3-dev` `gcc` `pkg-config` packages (ubuntu; these are needed because ubuntu does not ship `listsuites` nss tool, so it needs to be built on the fly)

How to run as jtreg:
See [github workflow](https://github.com/rh-openjdk/ssl-tests/blob/4756217e1dbc6d0a764dd878fd0e41b6264a9086/.github/workflows/test.yaml#L329).

**Comment by zzambers** [comment]
I have done some experiments:

I have first tried to add this as functional same way as CryptoTest:
https://github.com/zzambers/aqa-tests/commit/57ec63c56981ca80d92caf4e325c2b5c1a965f89
but that failed due to missing openssl tool:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/6990/

I have not seen a way to add system dependencies in functional tests, so I have tried external, where I saw docker is used and dependencies can be installed:
https://github.com/zzambers/aqa-tests/commit/e18746c220a95ad661a26f0dc445f0cf9010a025
that one was eventually successful:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7007/

**Comment by zzambers** [comment]
@smlambert I have just tested functional variant with one more fix [1], locally, on system where it has all dependencies installed and it passed. I think you have said in some meeting, that this variant would need dependencies added to playbook somewhere. Is that something to be added somewhere in this repo, or is that different repo? Maybe here? [2]

[1] https://github.com/zzambers/aqa-tests/tree/ssl-tests-wip
[2] https://github.com/adoptium/infrastructure/tree/master/ansible

**Comment by smlambert** [comment]
@zzambers - indeed for machine configuration (which we do via Ansible playbooks), we'd make the change in the playbooks in the infrastructure repo, https://github.com/adoptium/infrastructure.  For guidance there, perhaps connect with @steelhead31 or @Haroon-Khel this week

**Comment by sophia-guo** [comment]
In favour of https://github.com/adoptium/aqa-tests/pull/4835, close it.
