### ISSUE TITLE
Jenkins Generator: Allow lightweight checkout option

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/aqa-tests#4580]
Currently, the test job generator uses non-lightweight checkout because of a Jenkins issue when using variables for SCM Repo & Branch fields. This causes the full repo to be cloned to the Controller for each test job, which ends up consuming a great deal of disk space.
This has been partially(?) resolved in [JENKINS-42971](https://issues.jenkins.io/browse/JENKINS-42971). As far as I can tell, the solution only works for Branch, not Repo. I have asked for clarification in the issue.
What this means is we can switch to lightweight checkout for all the jobs that don't need a parameterized repo value. I am thinking all generated automatic jobs. Ie. everything except for Grinders etc.
Not sure if it would be beneficial to add a bool to the generator job to toggle lightweight and/or toggle hardcoded repo vs parameter.

**Comment by llxia** [comment]
Yes, I got the same result. The solution only works for the branch, not the repo.
```
stderr: fatal: '${ADOPTOPENJDK_REPO}' does not appear to be a git repository
fatal: Could not read from remote repository.
```

As for the solution, instead of having another bool parameter, we will set Branch Specifier as a parameter regardless. Only set Repository URL explicitly if LIGHT_WEIGHT_CHECKOUT=true. Otherwise, set Repository URL as a parameter. Once https://issues.jenkins.io/browse/JENKINS-42971 is fully resolved, we should remove LIGHT_WEIGHT_CHECKOUT parameter as LIGHT_WEIGHT_CHECKOUT=true should always be set. And both Repository URL Branch Specifier should be set as parameters.
