### ISSUE TITLE
jdk21: java/util/Properties/StoreReproducibilityTest failed on mac1014 passed on mac12

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4751]
Tests are available on 20+. History shows consistently failed on all mac1014 [ci.role.test&&hw.arch.x86&&(sw.os.osx||sw.os.mac)&&xcode10](https://ci.adoptium.net/label/ci.role.test&&hw.arch.x86&&%28sw.os.osx%7C%7Csw.os.mac%29&&xcode10/) and passed on [mac12](https://ci.adoptium.net/label/macos12/)

https://trss.adoptium.net/deepHistory?testId=64f6926017052c6715143752

```
19:03:54   stdout: [Current default timezone is sun.util.calendar.ZoneInfo[id="Europe/Dublin",offset=0,dstSavings=3600000,useDaylight=true,transitions=227,lastRule=java.util.SimpleTimeZone[id=Europe/Dublin,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]
19:03:54  ];
19:03:54   stderr: []
19:03:54   exitValue = 0
19:03:54  
19:03:54  java.lang.RuntimeException: Expected date comment Tue Sep 05 00:03:43 IST 2023 to be after Tue Sep 05 00:03:42 IST 2023 but was Mon Sep 04 19:33:43 IST 2023
19:03:54  	at StoreReproducibilityTest.assertCurrentDate(StoreReproducibilityTest.java:434)
19:03:54  	at StoreReproducibilityTest.testEmptySysPropValue(StoreReproducibilityTest.java:256)
19:03:54  	at StoreReproducibilityTest.main(StoreReproducibilityTest.java:71)
19:03:54  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
19:03:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
19:03:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:333)
19:03:54  	at java.base/java.lang.Thread.run(Thread.java:1583)
19:03:54  
19:03:54  JavaTest Message: Test threw exception: java.lang.RuntimeException
19:03:54  JavaTest Message: shutting down test

```

https://ci.adoptium.net/view/Test_openjdk/job/Test_openjdk21_hs_sanity.openjdk_x86-64_mac/124/console

**Comment by sophia-guo** [comment]
[The test ](https://github.com/openjdk/jdk21/blob/master/test/jdk/java/util/Properties/StoreReproducibilityTest.java#L420-L437) test if it can parse the time by the format "EEE MMM dd HH:mm:ss zzz uuuu" . Test failed if the default timezone is "Europe/Dublin". The reason is the Abbr of both  Irish Standard Time and  India Standard Time is same as IST. If the format "zzz" is "IST" it is parsed as  India Standard Time. In our case it is actually is  Irish Standard Time, which fail the test.

@zzambers thoughts? Could you please look at this?

**Comment by zzambers** [comment]
@sophia-guo sorry for late response, I was on PTO last week. I'll take a look.

**Comment by zzambers** [comment]
Looking into [JDK sources](https://github.com/openjdk/jdk21u/blob/master/src/java.base/share/classes/sun/util/resources/TimeZoneNames.java), some abbreviations of zone names are indeed ambiguous (root locale). In particular `IST` can be:
```
Irish Summer Time
Israel Standard Time
India Standard Time
```

I have found mention of this issue in [DateTimeFormatterBuilder](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/format/DateTimeFormatterBuilder.html#appendZoneText(java.time.format.TextStyle,java.util.Set))  class:
`
... Many textual zone names are not unique, such as CST can be for both "Central Standard Time" and "China Standard Time". In this situation, the zone id will be determined by the region information from formatter's locale and the standard zone id for that area, ...
`

Particular locale can give precedence to specific interpretation of abbreviation, to be used, when parsing local date. For example `IST` in [en_IE](https://github.com/openjdk/jdk21u/blob/ad222a46f93a6532c84269c39255e6caf479baad/src/jdk.localedata/share/classes/sun/util/resources/ext/TimeZoneNames_en_IE.java#L50) locale.

However `FORMATER` in this test has to use `ROOT` (US) locale (see [JDK-8282023](https://bugs.openjdk.org/browse/JDK-8282023); this is because [Properties.store](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/Properties.html#store(java.io.Writer,java.lang.String)) makes use of [Date.toString](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/Date.html#toString())) It does not seem like there is an easy solution using `FORMATER`, which would work for all zones out of box (given time format used by Properties.store).

Possible workarounds would be ether to avoid ambiguous time zone abbreviations by explicitly setting timezone in test. Or skipping test which [compares dates](https://github.com/openjdk/jdk21/blob/890adb6410dab4606a4f26a942aed02fb2f55387/test/jdk/java/util/Properties/StoreReproducibilityTest.java#L433).

**Comment by zzambers** [comment]
@sophia-guo Does it already have upstream openjdk bug, or should I create one?

**Comment by sophia-guo** [comment]
@zzambers I don't think there is upstream openjdk bug for this.

**Comment by zzambers** [comment]
I have created this issue:
https://bugs.openjdk.org/browse/JDK-8316540

I'll later prepare PR with fix.

**Comment by judovana** [comment]
The bug is was fixed for jdk/jdk by reseting the test to GMT (if i read it correctly).
In case of need it being  backported,  ProcessTools.createTestJvm is not in jdk8 (but is in 11 and up)

If you do nto wish to pull for some reason, I'm sure the failure is fasle negativum annd the machine canbe safely moved to GMT (not physically :) )

**Comment by sophia-guo** [comment]
The tests are available on 20+. No worries for jdk8.

**Comment by sophia-guo** [comment]
@judovana will it be backported to jdk21?

**Comment by zzambers** [comment]
@sophia-guo eventually I have only created openjdk bug, someone was faster with proposing fix (creating PR). Not sure whether backporting that fix for jdk21 is planned by it's author, but we can backport it ourselfs, if necessary.

**Comment by sophia-guo** [comment]
@zzambers the reason I'm asking is we might need to exclude it if it won't be backported.

**Comment by zzambers** [comment]
@sophia-guo I have opened backport for jdk21u:
https://github.com/openjdk/jdk21u/pull/221

**Comment by sophia-guo** [comment]
https://github.com/openjdk/jdk21u/commit/667e639964dcdfcdad52ea14cb8ac7e3576b9616 , close this one.
