### ISSUE TITLE
EXTRA_OPTIONS should append instead of prepend to the existing JVM options

### ISSUE THREAD

**Issue by JasonFengJ9** [adoptium/aqa-tests#4849]
Currently the `EXTRA_OPTIONS` could be overridden by an existing JVM option, for example, `-Xdump:java:events=vmstop` is specified at `EXTRA_OPTIONS`, and the actual JVM command is `-Xdump:java:events=vmstop ... -Xdump:system:none  ...`.  The option supplied has no effect.
The `EXTRA_OPTIONS` should append instead of prepend to the existing JVM options.

FYI @llxia

**Comment by llxia** [comment]
@annaibm could you take a look at this issue? Thanks

**Comment by llxia** [comment]
Please check where EXTRA_OPTIONS is contrustured and used. For example: 
https://github.com/search?q=repo%3Aadoptium%2Faqa-tests%20system%3Anone&type=code

**Comment by llxia** [comment]
The issue in openjdk did not get resolved yet.

**Comment by llxia** [comment]
Thanks @annaibm's verification. In openjdk test, https://github.com/adoptium/aqa-tests/blob/2ea383b607d7c1bbb18c67ad3d11fd5e77bbe0a0/openjdk/openjdk.mk#L177 , `EXTRA_OPTIONS` is appended.

<img width="1243" alt="image" src="https://github.com/adoptium/aqa-tests/assets/19273206/0da7974a-95de-4259-9398-c4ae841b284c">

This issue is resolved.

**Comment by JasonFengJ9** [comment]
Thank you @annaibm @llxia
