### ISSUE TITLE
Sanity.external openliberty-mp-tck test fails on unreleased JDK versions like 22 and 23

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#5117]
**Summary**

openliberty-mp-tck cannot find a docker image manifest file for unreleased jdk versions.

- JDK22: eclipse-temurin:22-jdk
- JDK23: eclipse-temurin:23-jdk

**Error message**

```
00:27:48       [exec] The test in the build_image() function is openliberty-mp-tck
00:27:48       [exec] #####################################################
00:27:48       [exec] INFO: docker build  --no-cache -t adoptopenjdk-openliberty-mp-tck-test:22-jdk-ubuntu-hotspot-full -f /home/jenkins/workspace/Test_openjdk22_hs_sanity.external_x86-64_linux/jvmtest/external/openliberty-mp-tck/dockerfile/22/jdk/ubuntu/Dockerfile.hotspot.full /home/jenkins/workspace/Test_openjdk22_hs_sanity.external_x86-64_linux/jvmtest/external/
00:27:48       [exec] #####################################################
00:27:48       [exec] Sending build context to Docker daemon  71.68kB
00:27:48       [exec] Step 1/25 : ARG IMAGE=eclipse-temurin:22-jdk
00:27:48       [exec] Step 2/25 : ARG OS=ubuntu
00:27:48       [exec] Step 3/25 : ARG IMAGE_VERSION=nightly
00:27:48       [exec] Step 4/25 : ARG TAG=22-jdk
00:27:48       [exec] Step 5/25 : FROM $IMAGE
00:27:48       [exec] manifest for eclipse-temurin:22-jdk not found: manifest unknown: manifest unknown
```

**Links**

https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.external_x86-64_linux/6/console
https://hub.docker.com/_/eclipse-temurin

**Details**

Looks like we don't make docker images for jdk22 and 23 yet. Will ask George if we need to create the relevant folders in the [docker repo](https://github.com/adoptium/containers) so we can start creating + uploading these images.

**Comment by adamfarley** [comment]
@gdams - Could you take a look at this, please?

**Comment by smlambert** [comment]
We now only produce official Docker Temurin images for versions that are 'officially released' (GA builds).  As per https://www.java.com/releases/, since JDK22 will only have its first official release in March 2024, and JDK23 in Sept 2024, we should disable the external tests on those versions.

Note: I believe in the past (under AdoptOpenJDK) we were publishing containers of EA builds also (not just GA builds), but since that is no longer the case, exclusion is the right approach (given we have no un-official Docker images to pull.

**Comment by smlambert** [comment]
auto exclude test openliberty_microprofile_tck ver=22+

**Comment by smlambert** [comment]
Workflow triggered by the comment above failed with
```
  /usr/bin/git push --force-with-lease origin autoTestPR-ieq40se:refs/heads/autoTestPR-ieq40se
  remote: Permission to adoptium/aqa-tests.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/adoptium/aqa-tests/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```
which may be caused by a config change to this repository (see https://github.com/actions/checkout/issues/417#issuecomment-1427951779).  Will need to check Otterdog settings to see if something changed (or if something needs to be changed).

Meantime, will need to create a manual PR to exclude this test target on 22+.

**Comment by smlambert** [comment]
Created but then closed https://github.com/adoptium/aqa-tests/pull/5118, in favour of https://github.com/adoptium/ci-jenkins-pipelines/pull/953.

**Comment by adamfarley** [comment]
Thanks Shelley! Closing now.
