### ISSUE TITLE
Add support for running custom serviceability jvmti test

### ISSUE THREAD

**Issue by fengxue-IS** [adoptium/aqa-tests#5357]
I'd like to request ability to run custom serviceability jvmti test.
Ideally with new test target:
`serviceability_jvmti_custom`
where a custom test path can be provided.

default test to run:
serviceability/jvmti/GetSystemProperty/JvmtiGetSystemPropertyTest.java

**Comment by fengxue-IS** [comment]
FYI @llxia

**Comment by llxia** [comment]
On second thought, instead of creating a separate test target for serviceability, maybe we can leverage the existing `hotspot_custom`
https://github.com/adoptium/aqa-tests/blob/feb08cae5a6334532d44446d54c43696d2673112/openjdk/playlist.xml#L98

Remove https://github.com/adoptium/aqa-tests/blob/feb08cae5a6334532d44446d54c43696d2673112/openjdk/playlist.xml#L118-L120 and disable `<impl>openj9</impl>` via `<disables>`. 

In this way, openj9 dev users can run any hotspot folder target via `TARGET=disabled.hotspot_custom`.

@LongyuZhang could you take care of this one? Thanks

**Comment by LongyuZhang** [comment]
Tested running with `TARGET: disabled.hotspot_custom`, and `CUSTOM_TARGET: serviceability/jvmti/GetSystemProperty/JvmtiGetSystemPropertyTest.java`.
The test runs but the `CUSTOM_TARGET` was not taken as `hotspot_custom` runs `HOTSPOT_CUSTOM_TARGET` ([link](https://github.com/adoptium/aqa-tests/blob/0a9e32cfa872e9e61d98c6d8897d430247ea9067/openjdk/openjdk.mk#L174)) instead.
Found a related open issue https://github.com/adoptium/aqa-tests/issues/4408, which needs to be resolved first.

**Comment by llxia** [comment]
just for the record, usage
```
TARGET=disabled.hotspot_custom
CUSTOM_TARGET=serviceability/jvmti/GetSystemProperty/JvmtiGetSystemPropertyTest.java

```

**Comment by LongyuZhang** [comment]
Close this issue as fixed by https://github.com/adoptium/aqa-tests/pull/5370.

**Comment by sophia-guo** [comment]
Note per #5370, for openj9,  hotspot_custom can only be used for serviceability jvmti test jdk19+ with the -nativepath set as hotspot native path ` -nativepath:"$(TESTIMAGE_PATH)/hotspot/jtreg/native`, which meets currently requirements. It won't work if tests requires openj9 nativepath. Better to add some comments or update some documents.

**Comment by sophia-guo** [comment]
I would prefer to add a custom serviceability jvmti test target instead of using hotspot_custom as a hack.

**Comment by LongyuZhang** [comment]
Updated the usage for openj9 via https://github.com/adoptium/aqa-tests/pull/5493:
```
TARGET=hotspot_custom_j9
CUSTOM_TARGET=serviceability/jvmti/GetSystemProperty/JvmtiGetSystemPropertyTest.java
```
