### ISSUE TITLE
sun_net_www_protocol_file_DirPermissionDenied test fails in jdk11

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#749]
Untriaged failure: 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_windows/79/testReport/sun_net_www_protocol_file_DirPermissionDenied/java/DirPermissionDenied/

Is it specific to Windows?  Is it reproducible?  Can we determine if its a known upstream bug (see [guidance for OpenJDK test defects](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-OpenJDK-Test-Defects)), or is it related to machine configuration?

**Comment by stooke** [comment]
Following the history of this file back, at one point it was suggested that jtreg could just do the cleanup after the test ran. [net-dev](http://mail.openjdk.java.net/pipermail/net-dev/2017-June/010836.html)
In fact, this is suggested in the jtreg FAQ.

**Comment by smlambert** [comment]
Ah, so maybe this is already in the bug database as a known upstream issue that we should be excluding?  https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-OpenJDK-Test-Defects

**Comment by smlambert** [comment]
I see it mention of this test for linux in this closed issue: https://bugs.openjdk.java.net/browse/JDK-7078355

**Comment by stooke** [comment]
As far as I can tell there's no open issue relating to this specific failure.

In the discussion for that test, a chmod was added to the shell script at cleanup time, and then later dropped when the shell script was converted into Java  - because it was apparently felt it was an obscure Linux box (which was running RHEL).  

It could be argued that the chmod should be restored (I'm happy to produce a PR), but it was for a Linux issue, not a Windows issue.  It could also be argued that the failure to cleanup is not part of the test and should be left to jtreg to cleanup.  

Unfortunately, I can't tell from Jenkins when the last successful run was, so I can't rule out a code change yet.  My next step is to try this locally and see what happens.

**Comment by adamfarley** [comment]
This symptom is still a problem.

Seen on Hotspot and J9, in the following tests:

java/lang/module/ModuleFinderTest.java
jdk/modules/scenarios/automaticmodules/RunWithAutomaticModules.java

Note that I'm unable to reproduce this issue locally, while I'm running outside of the framework. I checked the jtr file for the error message myself, presuming this error is coming from jtreg.

**Comment by adam-thorpe** [comment]
sun/net/www/protocol/file/DirPermissionDenied.java is still failing on jdk11, it was fixed on jdk13 and above here but needs backporting: https://bugs.openjdk.java.net/browse/JDK-8227422
The above 3 tests referenced by Adam don't seem to be failing anymore so I will unexclude them and update if they occur again in later nightlies

**Comment by smlambert** [comment]
Test is excluded under #760, closing this as dup of 760
